---
- name: restart apache
  service: name="{{ apache.service_name[os] }}" state=restarted must_exist=false

- name: reload apache
  service: name="{{ apache.service_name[os] }}" state=reloaded must_exist=false

- name: stop apache
  service: name="{{ apache.service_name[os] }}" state=stopped
