---
common:
  hwraid:
    enabled: True
    clients:
      - tw-cli
      - megacli
  ipmi:
    enabled: True
    serial_console: ttyS1
    state: probe
    baud_rate: 115200
  ntpd:
    servers: []
    #  - servertime.service.softlayer.com
  serial_console:
    enabled: True
    name: ttyS0
    baud_rate: 9600
  ssh_private_keys: []
  ssh:
    allow_from:
      - 0.0.0.0/0
      - ::/0
    disable_root: False
    disable_dns: True
  pip_version: 8.0.2
  setuptools_version: system
  ursula_monitoring:
    path: /opt/ursula-monitoring
    method: git # git|tar
    git_repo: https://github.com/blueboxgroup/ursula-monitoring.git
    git_rev: master
    tar_url: https://github.com/blueboxgroup/ursula-monitoring/archive/master.tar.gz
    tar_version: master
  system_tools:
    mcelog: True
    debian:
      lm_sensors_package: lm-sensors
      snmp_package: snmp
      packages:
        - acl
        - auditd
        - build-essential
        - curl
        - dstat
        - ethtool
        - tcpdump
        - telnet
        - git
        - htop
        - iftop
        - iotop
        - iperf
        - ltrace
        - mtr
        - netcat
        - pv
        - ruby1.9.1
        - ruby1.9.1-dev
        - smem
        - socat
        - tree
        - vim
        - cdpr
        - sysstat
        - logrotate
        - ntp
        - vlan
        - lvm2
        - libpam-cracklib
        - pciutils
    redhat:
      lm_sensors_package: lm_sensors
      snmp_package: net-snmp-utils
      packages:
        - acl
        - curl
        - dstat
        - ethtool
        - git
        - iotop
        - tcpdump
        - ltrace
        - nc
        - ruby-devel
        - ruby
        - socat
        - tree
        - vim
        - sysstat
        - logrotate
        - ntp
        - lvm2
        - cracklib
        - mlocate
        - cyrus-sasl-devel
  python:
    base_venv: "/opt/openstack/base"
    debian:
      system_packages:
        - python-pip
        - python-libxml2
        - python-lxml
        - python-greenlet
        - python-openssl
        - python2.7-dev
        - python-httplib2
        - python-software-properties
        - python-virtualenv
        - python-mysqldb
        - python-jinja2
        - cryptsetup
        - libffi-dev
        - libssl-dev
        - libxml2-dev
        - libxslt1-dev
      extra_packages: []
    redhat:
      system_packages:
        - python-pip
        - libxml2-python
        - python-lxml
        - python-greenlet
        - pyOpenSSL
        - python-devel
        - python-httplib2
        - python-virtualenv
        - MySQL-python
        - python-jinja2
        - cryptsetup
        - libffi-devel
        - openssl-libs
        - libxml2-devel
        - libxslt-devel
        - openssl-devel
        - libstdc++-static
        - gcc-c++
        - python-requests
        - uwsgi-plugin-python
      extra_packages:
        - pytz
        - pyopenssl
  packages_to_remove:
    - language-selector-common
  logs:
    - paths:
        - /var/log/audit/audit.log
      fields:
      type: syslog
      tags: audit,common
  logging:
    debug: False
    verbose: True
  monitoring:
    sensu_checks:
      check_lro:
        warning: False
        enabled: True
        devices: "{{ hostvars[inventory_hostname][hostvars[inventory_hostname].primary_interface|remove_vlan_tag]|net_physical_devices|join(',') }}"
      check_static_route:
        criticality: 'critical'
      check_raid:
        criticality: 'critical'
      vyatta:
        tunnels:
          criticality: 'critical'
    scan_for_log_errors: False
  os_tuning_params_clean:
    - { name: net.ipv4.tcp_syncookies }
    - { name: net.ipv4.tcp_synack_retries }

# Below is a ucarp config example:
network:
  ucarp:
    config: []
#    - vid:
#      contents: |
#        BIND_INTERFACE="bond0"
#        PASSWORD=""
#        SOURCE_ADDRESS=""
#        VIP_ADDRESS=""
#        UPSCRIPT="/usr/local/libexec/ucarp-vip-up"
#        DOWNSCRIPT="/usr/local/libexec/ucarp-vip-down"
#        OPTIONS="--shutdown"

openstack:
  gem_sources:
    - https://gem-mirror.openstack.blueboxgrid.com
