---
- name: install cinder controller services
  upstart_service: name={{ item }}
                   user=cinder
                   cmd=/usr/local/bin/{{ item }}
                   config_dirs=/etc/cinder
  when: os == 'ubuntu'
  with_items:
    - cinder-api
    - cinder-scheduler

- name: install cinder controller services (rhel source)
  systemd_service: name={{ item }}
                   user=cinder
                   cmd=/usr/local/bin/{{ item }}
                   config_dirs=/etc/cinder
  when: os == 'rhel' and openstack_install_method == 'source'
  with_items:
    - cinder-api
    - cinder-scheduler

- name: sync cinder database
  command: cinder-manage db sync
  when: database_create.changed or force_sync|default('false')|bool
  run_once: true
  changed_when: true
  notify: restart cinder services
  # we want this to always be changed so that it can notify the service restart
  tags: db-migrate

- name: trigger restart on upgrades
  debug:
    msg: "Triggering service restart for upgrade"
  changed_when: True
  notify: restart cinder services
  when: (code_has_changed | default('False') | bool and upgrade | default('False') | bool) or
        (ceph.enabled|default('False')|bool and upgrade_ceph | bool)

- meta: flush_handlers

- name: start cinder controller services
  service: name={{ item }} state=started
  with_items:
    - cinder-api
    - cinder-scheduler
  when: openstack_install_method != 'distro'

- name: start cinder controller services (rhel osp)
  service: name={{ item }} state=started
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler
  when: openstack_install_method == 'distro'

- name: Permit access to Cinder
  ufw: rule=allow to_port={{ endpoints.cinder.port.haproxy_api }} proto=tcp
  tags: ufw
  when: os == 'ubuntu'

- name: Permit access to Cinder
  firewalld:
    state: enabled
    permanent: true
    port: "{{ endpoints.cinder.port.haproxy_api }}/tcp"
  tags: firewall
  when: os == 'rhel'

- include: monitoring.yml
  tags:
    - monitoring
    - common
  when: monitoring.enabled|default('True')|bool
