---
- name: cinder control process check installation for non-distro installation
  sensu_process_check: service={{ item }}
  with_items:
    - cinder-api
    - cinder-scheduler
  notify: restart sensu-client
  when: openstack_install_method != 'distro'
 
- name: cinder control process check installation for non-distro installation
  sensu_process_check: service={{ item }}
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler
  notify: restart sensu-client
  when: openstack_install_method == 'distro' and os == 'rhel'

- name: cinder services check
  sensu_check: name=check-cinder-services plugin=check-cinder-services.sh
               use_sudo=true args="-z {{ cinder.monitoring.sensu_checks.check_cinder_services.criticality }}"
  notify: restart sensu-client

- include: nimble-monitoring.yml
  when: sensu.nimble_san_ip is defined

- name: cinder metrics
  template: src=etc/collectd/plugins/cinder.conf dest=/etc/collectd/plugins/cinder.conf
  notify: restart collectd
  when: collectd is defined and collectd.enabled|bool
  tags: collectd

- name: cinder sla metrics
  sensu_metrics_check: name=cinder-sla-metrics plugin=metrics-os-api.py
                       args='-S cinder --scheme {{ monitoring.graphite.host_prefix }}'
  notify: restart sensu-client
