---
dependencies:
  - role: endpoints
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: neutron
    logdata: "{{ neutron.logs }}"
  - role: openstack-source
    project_name: neutron
    project_rev: "{{ neutron.source.rev }}"
    rootwrap: True
    alternatives: "{{ neutron.alternatives }}"
    system_dependencies: "{{ neutron.source.system_dependencies }}"
    python_dependencies: "{{ neutron.source.python_dependencies }}"
    constrain: "{{ neutron.source.constrain }}"
    upper_constraints: "{{ neutron.source.upper_constraints }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: neutron
    rootwrap: True
    alternatives: "{{ neutron.alternatives }}"
    when: openstack_install_method == 'package' 
  - role: openstack-distro
    project_name: neutron
    dependent_packages: "{{ neutron.osp_sys_packages }}"
    rootwrap: True
    when: openstack_install_method == 'distro'
