---
- name: heat process check installation for non-distro installation
  sensu_process_check: service={{ item }}
  with_items:
    - heat-api
    - heat-api-cfn
    - heat-engine
  notify: restart sensu-client
  when: openstack_install_method != 'distro'
  
- name: heat process check installation for non-distro installation
  sensu_process_check: service={{ item }}
  with_items:
    - openstack-heat-api
    - openstack-heat-api-cfn
    - openstack-heat-engine
  notify: restart sensu-client
  when: openstack_install_method == 'distro' and os == 'rhel'

- name: heat-api check
  sensu_check: name=check-heat-api plugin=check-os-api.rb
               args="--service heat --criticality {{ heat.monitoring.sensu_checks.check_heat_api.criticality }}"
  notify: restart sensu-client

- name: heat sla metrics
  sensu_metrics_check: name=heat-sla-metrics plugin=metrics-os-api.py
                       args='-S heat --scheme {{ monitoring.graphite.host_prefix }}'
  notify: restart sensu-client
