---
# set ceph related variables for future tasks
- include: pool_names.yml
  delegate_to: "{{ groups['ceph_monitors'][0] }}"
  when: inventory_hostname == groups['ceph_osds'][0]
  tags: ['monitoring', 'openstack', 'control', 'glance', 'cinder', 'cinder-data', 'nova', 'nova-data', 'data', 'openstack-setup']

- name: verify disks have been provided
  fail: msg="please provide osd disks"
  when: ceph.disks is not defined or ceph.disks|length <= 0

- name: install dependencies
  package: name={{ item }} state=present
  with_items: "{{ ceph.osd_dep_pkgs }}"
  register: result
  until: result|succeeded
  retries: 5

- name: install bcache dependencies
  package: name={{ item }} state=present
  with_items: "{{ ceph.bcache_pkgs }}"
  when: "'ceph_osds_hybrid' in group_names"
  register: result
  until: result|succeeded
  retries: 5

- name: register admin.keyring
  slurp: src=/etc/ceph/ceph.client.admin.keyring
  register: admin_keyring
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"

- name: write admin.keyring
  copy:
    dest: "{{ admin_keyring['source'] }}"
    content: "{{ admin_keyring['content'] | b64decode }}"

- name: register ceph.keyring
  slurp: src=/var/lib/ceph/bootstrap-osd/ceph.keyring
  register: ceph_keyring
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"

- name: write ceph.keyring
  copy:
    dest: "{{ ceph_keyring['source'] }}"
    content: "{{ ceph_keyring['content'] | b64decode }}"

- name: delete default 'rbd' pool
  command: ceph osd pool delete rbd rbd --yes-i-really-really-mean-it
  register: poolout
  changed_when: poolout.stdout | search('removed')
  delegate_to: "{{ groups['ceph_monitors'][0] }}"
  when: inventory_hostname == groups['ceph_osds'][0] 

- include: standard.yml
  when: "'ceph_osds_ssd' in group_names"

- include: bcache.yml
  when: "'ceph_osds_hybrid' in group_names"

- include: system_tuning.yml
  tags: ceph-osd
