---
openstack_install_method: 'distro'
openstack_distro_type: 'osp'

stack_env: ci-full-centos
undercloud_cidr:
  - cidr: 192.168.0.0/22
state_path_base: /opt/stack/data

validate_certs: false

rhn_subscription:
  username: "{{ rhn_user }}" 
  password: "{{ rhn_pass }}"

etc_hosts:
  - name: "{{ fqdn }}"
    ip: "{{ floating_ip }}"

neutron:
  enable_external_interface: True
  lbaas:
    enabled: False

common:
  hwraid:
    enabled: False

logging:
  enabled: true
  follow:
    enabled: true
    global_fields:
      customer_id: "unknown"
      cluster_name: "unknown"
    logs:
      - paths:
          - /var/log/messages
        fields:
          type: syslog

serverspec:
  enabled: false

xtradb:
  galera_version: 3
  client_version: 56
  server_version: 56

haproxy:
  stats_group: root

keystone:
  uwsgi:
    method: port

heat:
  enabled: True

ironic:
  enabled: False

cinder:
  enabled: False
