---
stack_env: ci-full
ursula_os: 'ubuntu'
undercloud_cidr:
  - cidr: 192.168.0.0/22

state_path_base: /opt/stack/data

neutron:
  enable_external_interface: True
  lbaas:
    enabled: True

keystone:
  ldap_domain:
    enabled: True
    domain: users

serverspec:
  enabled: True
