---
- set_fact:
    ntpd_service_name: ntp
  when: os == 'ubuntu'
- set_fact:
    ntpd_service_name: ntpd
  when: os == 'rhel'

- name: install ntp.conf
  template:
    dest: /etc/ntp.conf
    src: etc/ntp.conf
    mode: 0644
    owner: root
  notify:
    - restart-ntp

- name: ntp service enabled
  service:
    name: "{{ ntpd_service_name }}"
    state: started
    enabled: true
