---
dependencies:
  - role: openstack-database
    database_name: neutron
  - role: neutron-common
  - role: sensu-check
  - role: collectd-plugin
    when: collectd is defined and collectd.enabled|bool
